### ISSUE TITLE
Upgrade guzzle to 6.*

### ISSUE THREAD

**Issue by thedotedge** [getjump/VkApiPHP#12]
Otherwise it's not possible to use latest guzzle in the project alongside vkapi:
```
  Problem 1
    - getjump/vk 0.4.0 requires guzzlehttp/guzzle 4.* -> no matching package found.
```

**Comment by atehnix** [comment]
What is the problem upgrade to Guzzle 6?

**Comment by TrogWarZ** [comment]
+1

**Comment by SerafimArts** [comment]
@thedotedge Mark this package as "Abandoned" please if u did not want supports him. It did not works on PHP 7.1 because you use Guzzle 4.*. This problem was be fixed in https://github.com/guzzle/guzzle/pull/1393 Guzzle 5.3
