### ISSUE TITLE
Как начать использовать библиотеку?

### ISSUE THREAD

**Issue by mevsme** [getjump/VkApiPHP#5]

**Comment by getjump** [comment]
1. Почитать про Composer, например на официальном сайте : https://getcomposer.org/
2. В packagist библиотека доступна, как "getjump/vk"
3. После установки, прочитав мануал по Composer, подключая файл автозагрузки от Composer имеем ленивую подгрузку библиотеки, далее смотрим README.md или главную страницу репозитория, там есть хорошее описание, что и как можно сделать.
3.a. Если вас интересует, как начать использовать именно Api, то возможно, вам стоит начать отсюда https://vk.com/dev/
