### ISSUE TITLE
Сбрасывается версия api

### ISSUE THREAD

**Issue by morder** [getjump/VkApiPHP#6]
Начал пробовать пример кода из примеров, для запуска нескольких запросов в одном
В итоге чтобы код версии API не сбрасывался, необходимо делать вот так

$vk = getjump\Vk\Core::getInstance()->apiVersion('5.27');
$js1 = $vk/*->apiVersion('5.27')*/->request('groups.getById', ['group_id' => 'XXXXX'])->toJs();
$js2 = $vk->apiVersion('5.27')->request('wall.get', ['owner_id' => '-XXXX', 'count' => '2'])->toJs();

Также заметил что для использования "execute", необходимо обязательно указывать access_token, без него не работает, хотя в доке указано что 
"Этот метод не требует прав доступа."
https://vk.com/dev/execute

**Comment by getjump** [comment]
С версиями исправил.

По поводу execute - не знаю. Ранее таких проблем не было, единственный совет, если внутри execute используются "некоторые" методы(необязательно даже те, которые требуют token), тогда может возникать такая ошибка.

**Comment by zhuharev** [comment]
@morder есть открытые методы(можно вызывать без `access_token`, например [users.get](https://vk.com/dev/users.get)), не требующие прав доступа(при авторизации `scope=0`, например [execute](https://vk.com/dev/execute)), требующие прав доступа(`scope=wall` или `scope=8192`, например [wall.post](https://vk.com/dev/wall.post))
