### ISSUE TITLE
Bug in 'extended' requests

### ISSUE THREAD

**Issue by yuraborue** [getjump/VkApiPHP#9]
Например запрос https://vk.com/dev/wall.get с параметром extended
```
$js = $vk->request('wall.get', ['owner_id' => 'SOME_ID', 'count' => 10, 'extended' => 1, 'offset' => 0])->toJs();
$result = $js1->execute()->response;
```
Содержит только поле items, без profiles и groups.

Я так понимаю эти поля теряются в конструкторе класса Response

пока решение которое нашел это инициализировать класс так
```
        $vk = Core::getInstance()->apiVersion('5.5')->createAs(function($data) { return $data; });
```

**Comment by getjump** [comment]
eca7053f05a368e7b3ff2e3b78e6d00ef9e1bf5d
92e8daddbdd1214664560f62b2b351ab698ff142
